### PR TITLE
Fix sensitive_validation.out on Windows

### PR DESCRIPTION
**Pull request by A-312**
fix: #300

Add support for test on Windows when they have several lines.

### CODE REVIEW

**Comment by A-312** [comment]
I got a fix for `Error: done() invoked with non-Error:` but the test doesn't pass

**Comment by A-312** [comment]
It works on Windows :)

**Comment by A-312** [comment]
_I forgot to rebase the first commit and the revert of this commit._

**Comment by madarche** [comment]
:+1:

**Comment by madarche** [comment]
@A-312 please open a new ticket if/when you need a new published version of Convict.

**Pull request merged**
