### PR TITLE
Updating Dependencies - Replacing Optimist

### LINKED ISSUE #149: Replace optimist which is deprecated
Replace optimist, which is deprecated (as noted in #125, thanks @sykaeh), by another module, maybe [minimist](https://www.npmjs.com/package/minimist). I'm not in favor of `commander` which does too many things for the small needs of convict.

### PR DESCRIPTION
**Pull request by LongLiveCHIEF**
- updated deprecated usage of `.eslintrc`, renamed to `.eslintrx.yml` (and updated eslint to `2.9`)
- updated moment from `2.12 => 2.13`
- incremented patch number for `istanbul`
- replaced `optimist` with `minimist`, closes #149

### CODE REVIEW

**Comment by madarche** [comment]
So far this is fine LongLiveCHIEF. But only some advertised dependency updates have been done (that is ESLint and Istanbul).

Do you want this to be merged (in which case you should update the title of this PR to reflect reality), or do you prefer that we wait for the full stuff?

Tip: Usually one does submit a PR only when all the commits are ready and finalized.

Thanks!

**Comment by LongLiveCHIEF** [comment]
> Tip: Usually one does submit a PR only when all the commits are ready and finalized.

So you're saying that the sky is blue? :-)  

I made a git-goof.  I didn't realize it until just now, but since I was [live-streaming this contribution](https://www.livecoding.tv/longlivechief/videos/vrdX1-open-source-saturdays), I was able to go back and see what I did.  I pushed the wrong branch, then opened the PR, thinking those commits were included. (~50:45 into the vid).

I can't get back to this machine for a few hours, so hang tight.

**Comment by madarche** [comment]
No problem. It was more to let you know
Cheers

**Comment by LongLiveCHIEF** [comment]
Something with `shrinkwrap` is causing me issues. I've never had a need to use `shrinkwrap` before, so will work on this when I have time to figure it out.

**Pull request closed without merging**
