### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by ahippler**
- validator ^11.1.0 -> ^13.6.0
- yargs-parser ^18.1.3 -> ^20.2.7
- moment ^2.24.0 -> ^2.29.1

### CODE REVIEW

**Comment by madarche** [comment]
@ahippler thank you, I'll take care of your MR in the next days. Thanks again.

**Comment by madarche** [comment]
Thanks @ahippler 👍‍‍

**Comment by ahippler** [comment]
@madarche could you please release the new version on npm?

**Comment by madarche** [comment]
Hello @ahippler. For this, please follow #393. I haven't the access to publish the release myself.

**Comment by madarche** [comment]
@ahippler I guess it could be handled today.

**Pull request merged**
