### PR TITLE
v1.0.0 and remove old deprecated formats ipv4 and ipv6

### PR DESCRIPTION
**Pull request by madarche**
@zaach I think this is the right time to publish a v1.0.0 for node-convict. To justify it a bit more, let's remove some old deprecations that everyone should have got rid of long ago (in Node.js time).

### CODE REVIEW

**Comment by madarche** [comment]
… and sorry @zaach wrt to the 2 releases you've just published at the moment!

**Comment by madarche** [comment]
With a v1.0.0 we will have a nice set of badges denoting the quality of node-convict.

**Comment by madarche** [comment]
So @zaach what about this v1.0.0 release that we seem to be many (at least 2 :-) ) to wish for ?

**Comment by madarche** [comment]
I'm done with all the small edits I did in the README.

**Comment by zaach** [comment]
:+1: Thanks!

**Comment by madarche** [comment]
Thanks @zaach !

**Pull request merged**
