### PR TITLE
Feat switch to jest

### PR DESCRIPTION
**Pull request by madarche**
Switch to Jest

### CODE REVIEW

**Comment by A-312** [comment]
🤔

**Comment by A-312** [comment]
I thought you refuse `mocha` because of the syntax `expect(variable).to.be.something` 😕

**Comment by madarche** [comment]
@A-312 I was convinced of the interest to switch from js-must. But should.js and chai.js were not good candidates because they both allow the use of property access for assertions cf. https://github.com/moll/js-must/#asserting-on-property-access. Chai.js documents the following as recommended `expect(true).to.be.true; // Recommended` cf. https://www.chaijs.com/api/bdd/ which is something we don't want to creep in Convict. And the good candidate also had to [not (ab)use prototype](https://medium.com/intrinsic/javascript-prototype-poisoning-vulnerabilities-in-the-wild-7bc15347c96). See also https://github.com/nodejs/node/pull/32279. In the end there was only Jest that fits.

**Comment by A-312** [comment]
I read a new time and I understand now: `expect(true).to.be.will_be_wrong_but_dont_throw;` 😕 This is not a good thing :(

**Pull request merged**
