### PR TITLE
Pass instance to coerce()

### PR DESCRIPTION
**Pull request by voodooattack**
This PR solves #109 and contains a test case.

The second argument to `coerce` is the `config` object, this can be used to implement placeholders and other advanced functionality:

```javascript
convict.addFormats({
  placeholder: {
    validate: function(val) {
      /* validate proper path here */
    },
    coerce: function(val, config) {
      return val.replace(/\$\{([\w\.]+)}/g, function(v,m) { return config.get(m); });
    }
  }
});

var conf = convict({
  env: {
    format: ['production', 'development'],
    default: 'development',
    env: 'NODE_ENV',
    doc: 'The environment that we\'re running in.'
  },
  configPath: {
    format: 'placeholder',
    default: '/path/to/config',
    doc: 'Path to configuration files.'
  },
  config: {
    format: 'placeholder',
    default: '${configPath}/${env}.json',
    doc: 'Path to configuration file.'
  }
});

conf.get('config'); /* "/path/to/config/development.json" */
```

### CODE REVIEW

**Comment by madarche** [comment]
Thanks @voodooattack :-)

@zaach could you review this PR please? This LGTM.

**Comment by zaach** [comment]
Clever! Could you squash the commits in to a single commit? Thanks.

**Comment by voodooattack** [comment]
@zaach All done. Sorry it took a bit of time; I'm not very experienced with git.

**Comment by zaach** [comment]
:+1:

**Comment by A-312** [comment]
This solution is stange because we suppose that *configPath* will be load after *config*. JSON.stringify and do after convict.loadFile can sort this object to abc order...

And a weird bug for your user like this one : 

```
//work
configPath: './',
config: 'c.json'
```

and : 

```
//don't work
config: 'c.json',
configPath: './'
```

That why this should be only done after a full loading of load/loadFile. I think it is you who should make a recursive function to change placeholder not convict. Or make a new function/event `compile` : 

```js 
convict.addCompiler('placeholder', (v) => /youregex/.replace(v, () => 'placeholder'))
convict.load({ config: '', configPath: '' })
convict.compile()
convict.validate()
```

**Comment by A-312** [comment]
And I don't understand why 'placeholder' is not anymore in the README.

**Pull request merged**
