### PR TITLE
Fix coercion issue (TypeError) with load and loadFile

### LINKED ISSUE #126: Coercion issue (TypeError) with convict.load and convict.loadFile
node-convict @ 1.1.2
### Error thrown

```
TypeError: Cannot read property 'get' of undefined
    at /home/steven/code/restau/config.js:11:72
    at String.replace (native)
    at Object.convict.addFormat.coerce [as placeholder] (/home/steven/code/restau/config.js:11:16)
    at coerce (/home/steven/code/restau/node_modules/convict/lib/convict.js:273:32)
    at /home/steven/code/restau/node_modules/convict/lib/convict.js:238:15
    at Array.forEach (native)
    at overlay (/home/steven/code/restau/node_modules/convict/lib/convict.js:235:21)
    at Object.rv.load (/home/steven/code/restau/node_modules/convict/lib/convict.js:378:7)
    at Object.<anonymous> (/home/steven/code/restau/config.js:42:6)
    at Module._compile (module.js:398:26)
```
### Cause
- [`coerce` function](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L267) requires a convict instance in the fourth param
- [`overlay` function](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L234) call `coerce` without convict instance because `overylay` has no reference to one
- [`load`](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L377) and [`loadFile`](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L384) functions don't give the convict instance reference to `overlay` ([378](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L378) and [388](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L388))
### How to reproduce it

``` javascript
'use strict';

const convict = require('convict');

convict.addFormat({
  name: "placeholder",
  validate: function(val) {
    /* validate proper path here */
  },
  coerce: function(val, config) {
    return val.replace(/\$\{([\w\.]+)}/g, function(v,m) { return config.get(m); }); /* line 11 */
  }
});

var conf = convict({
  env: {
    format: ['production', 'development'],
    default: 'development',
    env: 'NODE_ENV',
    doc: 'The environment that we\'re running in.'
  },
  configPath: {
    format: 'placeholder',
    default: '/path/to/config',
    doc: 'Path to configuration files.'
  },
  config: {
    format: 'placeholder',
    default: '${configPath}/${env}.json',
    doc: 'Path to configuration file.'
  }
});

conf.get('config');
// return "/path/to/config/development.json"

conf.set('config', '${configPath}/foo.json');
conf.get('config');
// return "/path/to/config/foo.json"

conf.load({ config: '${configPath}/bar.json' }); /* line 42 */
// throw "TypeError: Cannot read property 'get' of undefined"
```
### How to fix it

Transport the convict instance reference from `load` and `loadFile` to `coerce` with adding it in `overlay` last param.
### Pull request

I will make a PR in few minutes to fix that issue.

### PR DESCRIPTION
**Pull request by enten**
Fix #126: Coercion issue (TypeError) with convict.load and convict.loadFile

### CODE REVIEW

**Comment by enten** [comment]
:heartbeat:

**Comment by madarche** [comment]
@enten thanks for your PR! Could you include a test with it please? And the provided test should fail in the current code of convict. Thanks!

**Comment by gurpreetatwal** [comment]
@madarche @enten  I've created a failing test for `load`, a similar one can be created for `loadFile` as well

```js
  it('must coerce on load', function() {

    let conf = convict({
      test: {
        format: 'port',
      },
    });

    conf.load({test: '1234'});

    conf.get('test').must.be(1234);
    conf.validate();

  });
```

**Comment by madarche** [comment]
Thanks @gurpreetatwal . Your test is very helpful. Unfortunately @enten's patch doesn't fix the coercion issue.

From Convict's README, the coercion usecase is to coerce environmental variables from strings to their proper types when importing them. This is a needed and thus legitimate usecase for a configuration handler. And since the actual Convict's code is already too complicated in the coercion and overlay areas I'm sorry but no other usecases will be supported.

**Pull request closed without merging**
