### PR TITLE
Fix custom format object nested properties warning by checking for the item type instead of item format

### LINKED ISSUE #233: Object config values result in warning about undeclared properties
Hello,

I would like to suggest a small improvement over #213 from @mmcgahan.

We use multiple custom formats that are in the end nothing more than objects that we would like to validate in a specific way. We are receiving warnings when loading the base schema and not even loading configurations on top of it. Here's an example:

```javascript
const convict = require('convict');

const schema = {
  foo: {
    format: 'bar',
    default: {
      baz: 'blah',
    },
  },
};

convict.addFormats({ bar: { validate() {} } });
const config = convict(schema);
config.validate();
// Warning: configuration param 'foo.baz' not declared in the schema
```

Since `foo` is after all an object, we believe that the warning behavior there should be the same than for the format `Object`. Is there a known fix for that issue?

Otherwise, please have a look at #234.

### PR DESCRIPTION
**Pull request by Helias-Criouet**
This PR aims to improve #215 and fix #233. This works in our use-case but feel free to point out any undesired effect this might have.

### CODE REVIEW

**Comment by madarche** [comment]
Hello @Helias-Criouet, thanks for this PR! This PR LGTM, but Convict's code is complicated, anyone wanting to provide another review is thus welcome!

Apart from the modification suggestion above, for this PR to be accepted it's needed to provide a test and documentation demonstrating the new use you are promoting. Thanks again for the time you've invested in this!

**Comment by Helias-Criouet** [comment]
@madarche Done! Thanks for the feedback and let me know if anything else is needed.

**Comment by madarche** [comment]
@Helias-Criouet the tests are good! What's still needed:

* modify the code as suggested in my code review above
* a little update on the README

Cheers

**Comment by Helias-Criouet** [comment]
@madarche I'm not seeing any code review. Is it an issue on my side?

**Comment by Helias-Criouet** [comment]
@madarche PR updated :)

**Comment by Helias-Criouet** [comment]
I'm actually questioning the fact to modify the README file.

I'm not sure to see what to write in a hypothetical new "Custom formats" section as it seems to me all the necessary info is already in either the "Validation" or "Custom format checking" section. Any specific idea?

I actually think that my example, albeit simple, is pretty bad since it is basically re-implementing what `convict` does by default. It would simply be there for the sake of showcasing the already-described custom format feature on an object property.
Unfortunately, my better example ideas would take up a lot of space since they would involve bigger nested objects, and would therefore involve a lot more cognitive load on the reader, still without introducing anything *truly* new.

Since I'm not merging any new feature here, I feel I am not adding something of worth to the README but just making it less straightforward to read.

Would you agree to leave the README file as is?

Cheers!

**Comment by usmonster** [comment]
_bump_

**Comment by madarche** [comment]
OK, let's use this as it is. Thanks a lot @Helias-Criouet!

**Pull request merged**
