### PR TITLE
Add support for masking sensitive values

### LINKED ISSUE #187: Feature request: ability to mark sensitive values for masking in toString()
It can be useful, when an application starts, to print out what it has determined the configuration to be; this allows the user to determine whether their issue is with configuration or elsewhere. To that end, it would be nice if convict provided a way to flag certain values as sensitive and have them masked by `toString()`. To illustrate, consider this code sample:
```javascript
'use strict';
const convict = require('convict');

let config = convict({
  secretKey: {
    default: null,
    env: 'SECRET_KEY',
    sensitive: true
  },
  notSecret: {
    default: 'public'
  }
});

console.log("config.get('secretKey'):");
console.log(config.get('secretKey'));
console.log();
console.log("config.get('notSecret'):");
console.log(config.get('notSecret'));
console.log();
console.log('config.toString():');
console.log(config.toString());
```
Currently, this is what happens when it's executed:
```shellsession
scapeless:convictmask elyscape$ SECRET_KEY=this-is-a-secret node sensitive-demo.js 
config.get('secretKey'):
this-is-a-secret

config.get('notSecret'):
public

config.toString():
{
  "secretKey": "this-is-a-secret",
  "notSecret": "public"
}
```
What I am proposing is that, if a field has `sensitive: true` set on it, something like this happens instead:
```shellsession
scapeless:convictmask elyscape$ SECRET_KEY=this-is-a-secret node sensitive-demo.js 
config.get('secretKey'):
this-is-a-secret

config.get('notSecret'):
public

config.toString():
{
  "secretKey": xxx,
  "notSecret": "public"
}
```
`config.get('secretKey')` still returns the actual value, but when it's output through `config.toString()`, the actual value is masked and safe for logging.

Adding this behavior to `config.toString()` would, of course cause breakage if anybody is for some reason relying on that to be valid JSON, so it might make more sense to add another function (`config.toSafeString()` or something) that masks sensitive fields. That being said, doing that means that the following would then be unmasked, which while not a huge deal is somewhat less convenient than if it were masked:
```javascript
console.log(`The config is: ${conf}`); // ${conf} is translated internally to conf.toString()
```

### PR DESCRIPTION
**Pull request by elyscape**
Initial attempt. No tests yet; I'll add those once the approach is validated.

Resolves #187.

### CODE REVIEW

**Comment by elyscape** [comment]
@madarche Please take a look when you have a chance.

**Comment by madarche** [comment]
This looks promising! Thanks! Just please rename some variables and add the corresponding tests (be sure to tests the case when there are 2 fields with the same name but at a different depth level).

**Comment by elyscape** [comment]
@madarche The code with simple variable names was basically copied from `set()`. I refactored that code out such that `walk()` now has an optional parameter for initializing unset variables and now both `toString()` and `set()` use that. Working on tests now.

**Comment by elyscape** [comment]
Tests in place. I had to modify the test framework to support checking both the config structure and the output of `toString()`. @madarche, please review when you have a chance.

**Comment by elyscape** [comment]
Actually, I have another test I can add. Working on that now.

**Comment by elyscape** [comment]
Okay, it should be solid now. As a side note, it looks like the static tests aren't included in Istanbul's code coverage checks due to the way we're handling child processes. I'll look into fixing that and submit a separate PR if possible.

**Comment by madarche** [comment]
@elyscape very nice work. And the code base is even improved. Thanks a lot!

**Pull request merged**
