### PR TITLE
Support mapping env vars to multiple settings

### PR DESCRIPTION
**Pull request by twitchard**
Addresses issue #124

I didn't add an overridable option to toggle the old behavior and throw on envvar reuse. My argument is as follows:
1. I throught it would be confusing for a schema to load successfully, but then to start throwing errors about an invalid schema on the call to .validate().
2. I thought that adding a global, setting-independent optional parameter to the function call that loads the schema `convict(...)` would add too much complexity, because no such optional parameter already exists.
3. This allows for most user flexibility. If the user still wants to forbid multiple environment variables, they may write their own function to do it and pass their schema through it before initializing convict. Whereas, if the user wants to permit mapping env vars to multiple settings, it is impossible with the current behavior.
4. This is not a breaking change. This will not change any schemas which were considered valid.

If you're not persuaded, I would be happy to try a different approach along the lines of #2 in my list if you think that is best. Otherwise, I've also made a PR #188 that documents and adds a test for the current behavior.

### CODE REVIEW

**Comment by madarche** [comment]
Hello @twitchard. I really do appreciate the way you have prepared the 2 competing PRs. Thanks! For now I have accepted #188.

What do other interested parties think about this PR please?

**Comment by madarche** [comment]
I'm convinced by @twitchard' rationale. And I'm for accepting this PR. I plan to merge it just after #191 lands.

**Comment by madarche** [comment]
@twitchard could you rebase your PR and resolve the conflicts please? I would be very happy to then merge your PR. Thank you!

**Comment by twitchard** [comment]
Done!

**Comment by madarche** [comment]
You're so fast guys 😄

Thanks @twitchard!

**Pull request merged**
