### PR TITLE
Switch from JSHint to ESLint

### PR DESCRIPTION
**Pull request by pdehaan**

### CODE REVIEW

**Comment by madarche** [comment]
Super! Thanks @pdehaan !
@zaach could you merge this PR please?

**Comment by madarche** [comment]
@zaach I have read the whole commit and LGTM.

**Comment by madarche** [comment]
@zaach ? I'm waiting for you on this to go on with other PRs as @pdehaan's PR touches the `package.json` file. Thank you.

**Comment by zaach** [comment]
:+1:

**Pull request merged**
