### PR TITLE
resolves #222 accept args and env as parameters to convict function

### LINKED ISSUE #222: Support passing argv and env as arguments to convict function
The convict function should accept argv and/or env as arguments instead of relying exclusively on the process.argv and process.env globals. The benefit of adding these arguments is that it makes convict unit-test friendly and it allows convict to be used outside of a cli environment (for example, in an IDE).

Here's the current workaround:

```js
function solitaryConvict(schema, argv, env) {
  const oldArgv = process.argv
  const oldEnv = process.env
  const config = convict(schema)
  process.argv = oldArgv
  process.env = oldEnv
  return config
}
```

While this works, it's quite a crude workaround.

### PR DESCRIPTION
**Pull request by mojavelinux**
- add args and env as optional parameters to convict function
- extract process.env into getEnv() function
- extract process.argv.slice(2) into getArgs() function
- document new parameters and methods in README
- add test

### CODE REVIEW

**Comment by mojavelinux** [comment]
Is there there anything else I need to do to get this PR accepted?

**Comment by agalazis** [comment]
this is close to adapter support https://github.com/mozilla/node-convict/issues/227 yet it wouldn't solve the issue entirely since the adapter should also receive the schema (eg the schema could be extended to contain kms keys that it would take in to account. I think it still doable that way but I was thinking of it as a function returning promise but then again it makes the whole process of accessing environment variables async ....

**Comment by mojavelinux** [comment]
Now that 4.x is out, can we revisit this. It's very important for being able to use convict as a reusable utility library (within a framework) and not just coupled to a CLI tool.

**Comment by madarche** [comment]
@mojavelinux thanks for all your detailed explanations, your neat work **and** your patience. This PR is fine. Can you just resolve the conflict that has appeared recently please?

And then it will time for a v4.3, won't it?

**Comment by mojavelinux** [comment]
Thanks for recognizing my work. That means a lot. I'm proud to be a contributor to this project.

I've resolved the merge conflict by joining the two points that were in conflict. Thanks again!

**Comment by mojavelinux** [comment]
Thanks one more time, @madarche!

**Pull request merged**
