### PR TITLE
resolves #230 allow argument value to be falsy

### LINKED ISSUE #230: Unable to set options to zero or empty string via command line
This is with version 4.0.1.

Try with `index.js`:
```js
const convict = require('convict');
const config = convict({foo: {default: 'bar', arg: 'foo'}});
console.log(config.get('foo'));
```
and
```
>node index.js --foo 0
bar
>node index.js --foo 1
1
>node index.js --foo ""
bar
>node index.js --foo " "
<space>
```

### PR DESCRIPTION
**Pull request by mojavelinux**
- value of falsy argument should override default value

### CODE REVIEW

**Comment by mojavelinux** [comment]
This is basically the same issue that happened with environment variables. See https://github.com/mozilla/node-convict/commit/4e0ea03c481ceb4734f6aff5d2c0d2f98e1280a9 for a related fix.

**Comment by mojavelinux** [comment]
Is there anything I can do to move this PR along?

**Comment by madarche** [comment]
Good again! Thanks! And again, sorry for the delay!

**Comment by mojavelinux** [comment]
Thanks again, @madarche!

**Pull request merged**
