### PR TITLE
Fill out tests

### PR DESCRIPTION
**Pull request by elyscape**
This adds additional tests to check certain error cases that are currently untested. It also fixes a minor issue in the library where an Error object was concatenated with a string, in the process losing useful information such as the stacktrace.

### CODE REVIEW

**Comment by elyscape** [comment]
Remaining untested code:

`validate()`:
- [A key is not in the schema but strict validation is off](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L110)
- [A key is in the schema but unset](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L113)

`normalizeSchema()`:
- The schema node currently being normalized isn't an object ([if condition](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L165) followed by [untested else block](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L254))

`importArguments()`:
- [A field supports being set via args but isn't](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L269)

`addDefaultValues()`:
- [A nested object either has children or doesn't](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L281) (I'm not quite sure)
- [I'm not quite sure what this case is](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L283)

`overlay()`:
- [I'm not quite sure what this does either](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L296)

`coerce()`:
- [A field has `format` set to `'boolean'`](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L341)

`default()`:
- [The requested path is not part of the schema](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L456) (I think)

`validate()`:
- [A validation error occurs but `e.message` is somehow unset](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L554)

**Comment by elyscape** [comment]
Of these, my thoughts:

The code in `validate()`, `importArguments()`, `coerce()`, `default()`, and `validate()` should be relatively easy to add tests for. I'll look into those shortly.

--

The `else` block in `normalizeSchema()` is dead code as the `if` condition will always be true. The code before the `if` check has the following logic:

- [If `node` is an object and not an array and does not contain a `default` property, recursively normalize it and return](https://github.com/mozilla/node-convict/blob/v3.0.0/lib/convict.js#L150-L158)
- [If `node` is not an object or is an array or is null, assume it's a simple value and convert it into an object with that value being the default](https://github.com/mozilla/node-convict/blob/v3.0.0/lib/convict.js#L159-L161)

As such, if the code has reached the `if` block in question, either the function will have returned or `node` will be an object.

--

The remaining functions with untested code are `addDefaultValues()` and `overlay()`. @madarche, could you help me understand what the highlighted code in those functions is doing?

**Comment by elyscape** [comment]
Update: the untested code in `default()` is also dead code. `o`, the variable it is testing, is the return value of `walk()`, which cannot return `undefined`; at each level, it checks if it is being asked to retrieve something from the schema that does not exist and, if so, throws an `Error`.

**Comment by elyscape** [comment]
Double update: `cloneDeep(undefined)` returns `undefined`, so that check isn't even necessary.

**Comment by madarche** [comment]
@elyscape I'm afraid I can't tell you more than what you know now. I've added test coverage in the first place to do the job you are doing but I've never had the time.

So I'm totally OK (and grateful!) for you to remove all what looks like dead code. Once you're done (tell me) I'll try your branch on many applications that heavily rely on Convict and use it in different ways. And if the newly reduced-Convict works still as intended I'll merge this PR!

**Comment by elyscape** [comment]
Update on `validate()`: [it is impossible to turn off validation entirely](https://github.com/mozilla/node-convict/blob/v3.0.0/lib/convict.js#L524), with `strictValidation` defaulting to `'warn'` if you leave it unset or try to set it to `false`. As such, [this check for `!p` is dead code](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L110); any time `!p` would be true, the preceding check for `strictValidation && !p` will also be true, since `strictValidation` is always going to be truthy, and it returns.

**Comment by elyscape** [comment]
The other untested path on `validate()` can't easily be tested without resolving a functionality issue, which I'll raise in a separate PR.

**Comment by elyscape** [comment]
Issue raised as #193. I'll do some digging into `addDefaultValues()` and `overlay()` and see about adding tests for those.

**Comment by elyscape** [comment]
`addDefaultValues()`:
[`Object.keys(kids).length` will be 0](https://github.com/mozilla/node-convict/blob/v3.0.0/lib/convict.js#L276) if the field provided is provided in the schema as an empty object (and, as far as I can tell, only then). The result of this check being in place, however, is that providing an empty object as a simple default to convict results in the field not existing in the resultant object, which is unique and probably unintended behavior. For example:
```javascript
'use strict';
const convict = require('convict');

let config = convict({
  empty: {},
  bool: false,
  string: 'string'
});

config.get(); // -> {bool: false, string: 'string'}
config.get('empty'); // throws Error: cannot find configuration param 'empty'
```
Should I remove this check to restore the expected behavior?

---

As far as I can tell, since `addDefaultValues()` is only called during initialization, if `p.properties` does not exist, then the field being processed is a leaf field (i.e. not the parent of nested fields). Additionally, since each member of the schema is processed exactly once by the function, `c` (which holds the current state of the being-generated config object) will not have a property for `name`. Furthermore, since `normalizeSchema()` is called before this, `p` will necessarily have a property called `default`. This makes [this check](https://github.com/mozilla/node-convict/blob/v3.0.0/lib/convict.js#L278) unnecessary.

**Comment by elyscape** [comment]
`overlay()`:
This function takes all the fields from `from`, coerces them according to the formats in `schema`, and then sets the resulting values in `to`. [The untested codepath in `overlay()`](https://coveralls.io/builds/10814181/source?filename=lib%2Fconvict.js#L296) handles the case where you're applying an object over something that either isn't an object or doesn't exist:
```javascript
'use strict';
const convict = require('convict');

let config = convict({});

config.load({parent: {child: 'value'} }); // to[k] is undefined -> isObj(to[k]) is false -> set to[k] to {}
config.load({parent: {child: 'new value'} }); // to[k] == {child: 'value'} -> isObj(to[k]) is true -> do nothing
```
I'll add a test for that.

**Comment by elyscape** [comment]
@madarche Thinking it over, the check mentioned in [this comment](https://github.com/mozilla/node-convict/pull/192#issuecomment-289904716) may cause other problems if it's removed, as that would mean that the schema won't have fully undergone normalization. I've added a test for the current behavior as part of testing the other shorthand behavior, though I'm not sure if this is quite the right approach to be taking. The other way to deal with it would be to add a check during schema normalization for empty objects and normalize them like other items. That could probably be done by changing [this line](https://github.com/mozilla/node-convict/blob/v3.0.0/lib/convict.js#L150) to:
```javascript
if (typeof node === 'object' && !Array.isArray(node) && !('default' in node) && Object.keys(node).length > 0) {
```
and changing [this line](https://github.com/mozilla/node-convict/blob/v3.0.0/lib/convict.js#L159) to:
```javascript
} else if (typeof node !== 'object' || Array.isArray(node) || node === null || Object.keys(node).length === 0) {
```

As an aside, the tests for default shorthands revealed that trying to use shorthands for `null` would crash. I have added a fix for that to this pull request.

**Comment by elyscape** [comment]
In any event, this should be ready for testing and potentially merge now.

**Comment by madarche** [comment]
@elyscape OK. I'll test. Expect answer in something like 2 days. Again **thanks a lot**.

A side note: if there is any uncertainty about the behavior of the new reduced-Convict, the next release will be a major release, so nobody will upgrade without notice and without taking care to validate.

**Comment by elyscape** [comment]
Sounds good! Once this gets merged, should I submit another pull request supporting `someField: {}` as shorthand for default empty objects? And/or should I add it to this? Also, when you get a chance, please take a look at #193.

Thanks for your help.

**Comment by madarche** [comment]
@elyscape I have run all the automated tests of all the applications we have that use convict, and all but one are working fine. I'm investigating what causes problems in this one case.

**Comment by madarche** [comment]
@elyscape the one application which had problems was not making a good usage of Convict. So your modifications are good! Thanks a lot!

**Pull request merged**
