### PR TITLE
Fixes #73, removes validator.check from README.md and adds valid form…

### LINKED ISSUE #73: Documentation using deprecated `validator.check`
In the validation section of the README.md, it uses `validator.check`, which disappeared from validator a long time ago. I've created a PR to remove that and show a valid example of a custom format function.

### PR DESCRIPTION
**Pull request by mmerkes**
…at checker

### CODE REVIEW

**Comment by madarche** [comment]
@mmerkes thanks for this PR that will nicely improve the doc!

Some remarks:

* Your PR should also remove the line `var check = require('validator').check;`
* Your PR should better use the `addFormat` method as shown in the [format-tests.js](https://github.com/mozilla/node-convict/blob/master/test/format-tests.js#L29) file

**Comment by mmerkes** [comment]
Thanks fro the feedback! I will update.

**Comment by mmerkes** [comment]
@madarche I tidied up the example and added another example using `convict.addFormat()` per your suggestion.

**Comment by madarche** [comment]
OK, it's very convincing :-) Thanks.

@zaach could you merge this PR please?

**Comment by zaach** [comment]
:+1:

**Comment by mmerkes** [comment]
Cool. Thanks for review, discussion and merge! I can very persuasive ;)

**Pull request merged**
