### PR TITLE
Two new tests (and bug fix)

### PR DESCRIPTION
**Pull request by voodooattack**
Loading a file that overrides an object can cause problems. ~~I was unable to find the source of this bug.~~

Bug found and fixed. Although I'm not sure if my solution is clean.

### CODE REVIEW

**Comment by madarche** [comment]
Thanks @voodooattack! LGTM. @zaach could you review the PR please?

**Comment by vladikoff** [comment]
:+1:

**Comment by madarche** [comment]
Thanks again @vladikoff!

**Comment by voodooattack** [comment]
Excellent, thank you all.

**Pull request merged**
