### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by madarche**

### CODE REVIEW

**Comment by madarche** [comment]
@vladikoff could you merge this PR too please?

**Comment by vladikoff** [comment]
looks like no breaking changes here https://github.com/chriso/validator.js/blob/master/CHANGELOG.md

**Comment by madarche** [comment]
Yes, no breaking changes in validator.js. I've checked the changelogs of all the proposed dependency updates before submitting this PR and everything seems alright. Also I've got different projects using `convict` and use them as additional tests when doing those global dependency upgrades.

Thanks!

**Comment by madarche** [comment]
Seems to me it's the right time to cut a 1.1.0 version. What do you think?

**Pull request merged**
