### PR TITLE
Update Precendence order documentation according implementation

### LINKED ISSUE #208: Readme precedence lists load as being equivalent to set
The readme for 3.0.0 states:

> Precedence order
> 
> When merging configuration values from different sources, Convict follows precedence rules. The order, from lowest to highest, is:
> 
> Default value
> File (config.loadFile())
> Environment variables
> Command line arguments
> Set and load calls (config.set() and **config.load()**)

But as per the code and the conversation in issue #50 config.load appears to be at the precedence level of config.loadFile, not config.set.

### LINKED ISSUE #211: Precendence order
Precendence order

I try to test Windows, but do not work following.

**When merging configuration values from different sources, Convict follows precedence rules. The order, from lowest to highest, is:

1.Default value
2.File (config.loadFile())
3.Environment variables
4.Command line arguments
5.Set and load calls (config.set() and config.load())**

In Mac computer Precendence order is work well, **But In Windows computer belows order** 

1.Default value
2.File (config.loadFile())
**3.Set and load calls (config.set() and config.load())**
**4.Environment variables**
5.Command line arguments

Set and load calls < Environment variables 

In Windows, Set and load calls is not highes order.

### PR DESCRIPTION
**Pull request by zaverden**
Fixes #211 
Fixes #208

### CODE REVIEW

**Comment by zaverden** [comment]
@A-312 could you check this out please? this is a documentation update according our discussion in #211. Does it look OK, or I should change it to be more clear?

**Comment by A-312** [comment]
I don't know, after looking this part, I don't like the current integration. We should have something like that : `config.loadExternal(['env', 'arg'])`. Or rewrite all the content of this paragraph.

After a long reflection, I think this can be better : 

> When merging configuration values from different sources, Convict follows precedence rules. The order, from lowest to highest, for `config.loadFile(file)` and `config.load(json)` is :
>
> 1. Default value ;
> 2. File or json set in function argument ;
> 3. Environment variables (only used when `env` property is set in schema) ;
> 4. Command line arguments (only used when `arg` property is set in schema; ).
>
> Environment variables and Command line arguments can be overridden using the `env` or `args` option of the convict function `convict(schema, {env: {}, arg: {}})` ???? **<--- check this part**
 
**I don't understand :** *can be overridden using the `env|args` option of the convict function* -> I think [this part is not in the doc](https://github.com/mozilla/node-convict/blob/master/lib/convict.js#L479). If I understand we can do `convict(schema, opt)`, is not it ?

We speak only about loadFile and load because `set` have priority only if is call after `load` because : 

```js
const config = convict({ port: { default: 3000 } }
config.load({ port: 8080 });
console.log(config.get('port')); // 8080
config.set('port', 433);
console.log(config.get('port')); // 443
config.load({ port: 9000 });
console.log(config.get('port')); // 9000
```

**Comment by zaverden** [comment]
@A-312 Thank you for a review. I did not think about complete rewrite of this block, but it make sense in order to make it clear. 

I'll update the PR later

**Comment by A-312** [comment]
ping @zaverden

**Comment by zaverden** [comment]
@A-312 sorry for delay.

I have updated description and moved _can be overridden using the env|args option_ to a separate section

**Comment by A-312** [comment]
This PR is ready

**Comment by A-312** [comment]
@madarche This one is ready

**Comment by A-312** [comment]
@zaverden Can you rebase your PR in mozilla:feat-multi-packages-split ? Is the branch for the next update (6.0.0).

**Comment by zaverden** [comment]
@A-312 done

**Pull request merged**
